pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t mgopaul/example-webserver .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run mgopaul/example-webserver /test.sh
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u mgopaul -p $PASS
      - docker push mgopaul/example-webserver
